/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProtocolDataProviderABI } from "./ProtocolDataProviderABI";
export * as factories from "./factories";
export { ProtocolDataProviderABI__factory } from "./factories/ProtocolDataProviderABI__factory";
