/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace DataTypes {
  export type EModeCategoryLegacyStruct = {
    ltv: BigNumberish;
    liquidationThreshold: BigNumberish;
    liquidationBonus: BigNumberish;
    priceSource: string;
    label: string;
  };

  export type EModeCategoryLegacyStructOutput = [
    number,
    number,
    number,
    string,
    string
  ] & {
    ltv: number;
    liquidationThreshold: number;
    liquidationBonus: number;
    priceSource: string;
    label: string;
  };

  export type ReserveConfigurationMapStruct = { data: BigNumberish };

  export type ReserveConfigurationMapStructOutput = [BigNumber] & {
    data: BigNumber;
  };

  export type ReserveDataLegacyStruct = {
    configuration: DataTypes.ReserveConfigurationMapStruct;
    liquidityIndex: BigNumberish;
    currentLiquidityRate: BigNumberish;
    variableBorrowIndex: BigNumberish;
    currentVariableBorrowRate: BigNumberish;
    currentStableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    id: BigNumberish;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    accruedToTreasury: BigNumberish;
    unbacked: BigNumberish;
    isolationModeTotalDebt: BigNumberish;
  };

  export type ReserveDataLegacyStructOutput = [
    DataTypes.ReserveConfigurationMapStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    configuration: DataTypes.ReserveConfigurationMapStructOutput;
    liquidityIndex: BigNumber;
    currentLiquidityRate: BigNumber;
    variableBorrowIndex: BigNumber;
    currentVariableBorrowRate: BigNumber;
    currentStableBorrowRate: BigNumber;
    lastUpdateTimestamp: number;
    id: number;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    accruedToTreasury: BigNumber;
    unbacked: BigNumber;
    isolationModeTotalDebt: BigNumber;
  };

  export type CollateralConfigStruct = {
    ltv: BigNumberish;
    liquidationThreshold: BigNumberish;
    liquidationBonus: BigNumberish;
  };

  export type CollateralConfigStructOutput = [number, number, number] & {
    ltv: number;
    liquidationThreshold: number;
    liquidationBonus: number;
  };

  export type EModeCategoryBaseConfigurationStruct = {
    ltv: BigNumberish;
    liquidationThreshold: BigNumberish;
    liquidationBonus: BigNumberish;
    label: string;
  };

  export type EModeCategoryBaseConfigurationStructOutput = [
    number,
    number,
    number,
    string
  ] & {
    ltv: number;
    liquidationThreshold: number;
    liquidationBonus: number;
    label: string;
  };

  export type ReserveDataStruct = {
    configuration: DataTypes.ReserveConfigurationMapStruct;
    liquidityIndex: BigNumberish;
    currentLiquidityRate: BigNumberish;
    variableBorrowIndex: BigNumberish;
    currentVariableBorrowRate: BigNumberish;
    __deprecatedStableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    id: BigNumberish;
    liquidationGracePeriodUntil: BigNumberish;
    aTokenAddress: string;
    __deprecatedStableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    accruedToTreasury: BigNumberish;
    unbacked: BigNumberish;
    isolationModeTotalDebt: BigNumberish;
    virtualUnderlyingBalance: BigNumberish;
  };

  export type ReserveDataStructOutput = [
    DataTypes.ReserveConfigurationMapStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    number,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    configuration: DataTypes.ReserveConfigurationMapStructOutput;
    liquidityIndex: BigNumber;
    currentLiquidityRate: BigNumber;
    variableBorrowIndex: BigNumber;
    currentVariableBorrowRate: BigNumber;
    __deprecatedStableBorrowRate: BigNumber;
    lastUpdateTimestamp: number;
    id: number;
    liquidationGracePeriodUntil: number;
    aTokenAddress: string;
    __deprecatedStableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    accruedToTreasury: BigNumber;
    unbacked: BigNumber;
    isolationModeTotalDebt: BigNumber;
    virtualUnderlyingBalance: BigNumber;
  };

  export type UserConfigurationMapStruct = { data: BigNumberish };

  export type UserConfigurationMapStructOutput = [BigNumber] & {
    data: BigNumber;
  };
}

export interface PoolABIInterface extends utils.Interface {
  functions: {
    "getEModeCategoryData(uint8)": FunctionFragment;
    "FLASHLOAN_PREMIUM_TOTAL()": FunctionFragment;
    "getReserveData(address)": FunctionFragment;
    "deposit(address,uint256,address,uint16)": FunctionFragment;
    "getLiquidationLogic()": FunctionFragment;
    "getReservesList()": FunctionFragment;
    "getUserAccountData(address)": FunctionFragment;
    "syncRatesState(address)": FunctionFragment;
    "getEModeCategoryCollateralConfig(uint8)": FunctionFragment;
    "updateBridgeProtocolFee(uint256)": FunctionFragment;
    "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "configureEModeCategory(uint8,(uint16,uint16,uint16,string))": FunctionFragment;
    "repayWithATokens(address,uint256,uint256)": FunctionFragment;
    "getSupplyLogic()": FunctionFragment;
    "setUserEMode(uint8)": FunctionFragment;
    "updateFlashloanPremiums(uint128,uint128)": FunctionFragment;
    "MAX_NUMBER_RESERVES()": FunctionFragment;
    "repay(address,uint256,uint256,address)": FunctionFragment;
    "getBridgeLogic()": FunctionFragment;
    "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)": FunctionFragment;
    "getEModeCategoryBorrowableBitmap(uint8)": FunctionFragment;
    "getReserveDataExtended(address)": FunctionFragment;
    "getBorrowLogic()": FunctionFragment;
    "getReservesCount()": FunctionFragment;
    "supply(address,uint256,address,uint16)": FunctionFragment;
    "getFlashLoanLogic()": FunctionFragment;
    "POOL_REVISION()": FunctionFragment;
    "getEModeCategoryLabel(uint8)": FunctionFragment;
    "finalizeTransfer(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "ADDRESSES_PROVIDER()": FunctionFragment;
    "initReserve(address,address,address,address)": FunctionFragment;
    "getEModeLogic()": FunctionFragment;
    "flashLoanSimple(address,address,uint256,bytes,uint16)": FunctionFragment;
    "getReserveNormalizedVariableDebt(address)": FunctionFragment;
    "configureEModeCategoryBorrowableBitmap(uint8,uint128)": FunctionFragment;
    "getReserveNormalizedIncome(address)": FunctionFragment;
    "borrow(address,uint256,uint256,uint16,address)": FunctionFragment;
    "resetIsolationModeTotalDebt(address)": FunctionFragment;
    "mintToTreasury(address[])": FunctionFragment;
    "backUnbacked(address,uint256,uint256)": FunctionFragment;
    "BRIDGE_PROTOCOL_FEE()": FunctionFragment;
    "liquidationCall(address,address,address,uint256,bool)": FunctionFragment;
    "configureEModeCategoryCollateralBitmap(uint8,uint128)": FunctionFragment;
    "getPoolLogic()": FunctionFragment;
    "withdraw(address,uint256,address)": FunctionFragment;
    "getUserEMode(address)": FunctionFragment;
    "getConfiguration(address)": FunctionFragment;
    "rescueTokens(address,address,uint256)": FunctionFragment;
    "setLiquidationGracePeriod(address,uint40)": FunctionFragment;
    "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "getUserConfiguration(address)": FunctionFragment;
    "syncIndexesState(address)": FunctionFragment;
    "getVirtualUnderlyingBalance(address)": FunctionFragment;
    "mintUnbacked(address,uint256,address,uint16)": FunctionFragment;
    "getReserveAddressById(uint16)": FunctionFragment;
    "FLASHLOAN_PREMIUM_TO_PROTOCOL()": FunctionFragment;
    "getEModeCategoryCollateralBitmap(uint8)": FunctionFragment;
    "setUserUseReserveAsCollateral(address,bool)": FunctionFragment;
    "dropReserve(address)": FunctionFragment;
    "setConfiguration(address,(uint256))": FunctionFragment;
    "setReserveInterestRateStrategyAddress(address,address)": FunctionFragment;
    "getLiquidationGracePeriod(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getEModeCategoryData"
      | "FLASHLOAN_PREMIUM_TOTAL"
      | "getReserveData"
      | "deposit"
      | "getLiquidationLogic"
      | "getReservesList"
      | "getUserAccountData"
      | "syncRatesState"
      | "getEModeCategoryCollateralConfig"
      | "updateBridgeProtocolFee"
      | "repayWithPermit"
      | "configureEModeCategory"
      | "repayWithATokens"
      | "getSupplyLogic"
      | "setUserEMode"
      | "updateFlashloanPremiums"
      | "MAX_NUMBER_RESERVES"
      | "repay"
      | "getBridgeLogic"
      | "flashLoan"
      | "getEModeCategoryBorrowableBitmap"
      | "getReserveDataExtended"
      | "getBorrowLogic"
      | "getReservesCount"
      | "supply"
      | "getFlashLoanLogic"
      | "POOL_REVISION"
      | "getEModeCategoryLabel"
      | "finalizeTransfer"
      | "initialize"
      | "ADDRESSES_PROVIDER"
      | "initReserve"
      | "getEModeLogic"
      | "flashLoanSimple"
      | "getReserveNormalizedVariableDebt"
      | "configureEModeCategoryBorrowableBitmap"
      | "getReserveNormalizedIncome"
      | "borrow"
      | "resetIsolationModeTotalDebt"
      | "mintToTreasury"
      | "backUnbacked"
      | "BRIDGE_PROTOCOL_FEE"
      | "liquidationCall"
      | "configureEModeCategoryCollateralBitmap"
      | "getPoolLogic"
      | "withdraw"
      | "getUserEMode"
      | "getConfiguration"
      | "rescueTokens"
      | "setLiquidationGracePeriod"
      | "supplyWithPermit"
      | "getUserConfiguration"
      | "syncIndexesState"
      | "getVirtualUnderlyingBalance"
      | "mintUnbacked"
      | "getReserveAddressById"
      | "FLASHLOAN_PREMIUM_TO_PROTOCOL"
      | "getEModeCategoryCollateralBitmap"
      | "setUserUseReserveAsCollateral"
      | "dropReserve"
      | "setConfiguration"
      | "setReserveInterestRateStrategyAddress"
      | "getLiquidationGracePeriod"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getEModeCategoryData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidationLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "syncRatesState",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryCollateralConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBridgeProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "configureEModeCategory",
    values: [BigNumberish, DataTypes.EModeCategoryBaseConfigurationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithATokens",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setUserEMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFlashloanPremiums",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NUMBER_RESERVES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBridgeLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [
      string,
      string[],
      BigNumberish[],
      BigNumberish[],
      string,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryBorrowableBitmap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveDataExtended",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlashLoanLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_REVISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryLabel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTransfer",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoanSimple",
    values: [string, string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedVariableDebt",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "configureEModeCategoryBorrowableBitmap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedIncome",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resetIsolationModeTotalDebt",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToTreasury",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "backUnbacked",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationCall",
    values: [string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "configureEModeCategoryCollateralBitmap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEMode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfiguration",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidationGracePeriod",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyWithPermit",
    values: [
      string,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfiguration",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "syncIndexesState",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVirtualUnderlyingBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintUnbacked",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveAddressById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryCollateralBitmap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserUseReserveAsCollateral",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "dropReserve", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setConfiguration",
    values: [string, DataTypes.ReserveConfigurationMapStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveInterestRateStrategyAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidationGracePeriod",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEModeCategoryData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidationLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncRatesState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryCollateralConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBridgeProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureEModeCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithATokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserEMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFlashloanPremiums",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NUMBER_RESERVES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBridgeLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryBorrowableBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveDataExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFlashLoanLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_REVISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flashLoanSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedVariableDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureEModeCategoryBorrowableBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resetIsolationModeTotalDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backUnbacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIDGE_PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureEModeCategoryCollateralBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserEMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidationGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncIndexesState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVirtualUnderlyingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintUnbacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveAddressById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryCollateralBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserUseReserveAsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveInterestRateStrategyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidationGracePeriod",
    data: BytesLike
  ): Result;

  events: {
    "BackUnbacked(address,address,uint256,uint256)": EventFragment;
    "Borrow(address,address,address,uint256,uint8,uint256,uint16)": EventFragment;
    "FlashLoan(address,address,address,uint256,uint8,uint256,uint16)": EventFragment;
    "IsolationModeTotalDebtUpdated(address,uint256)": EventFragment;
    "LiquidationCall(address,address,address,uint256,uint256,address,bool)": EventFragment;
    "MintUnbacked(address,address,address,uint256,uint16)": EventFragment;
    "MintedToTreasury(address,uint256)": EventFragment;
    "Repay(address,address,address,uint256,bool)": EventFragment;
    "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "ReserveUsedAsCollateralDisabled(address,address)": EventFragment;
    "ReserveUsedAsCollateralEnabled(address,address)": EventFragment;
    "Supply(address,address,address,uint256,uint16)": EventFragment;
    "UserEModeSet(address,uint8)": EventFragment;
    "Withdraw(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BackUnbacked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Borrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FlashLoan"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "IsolationModeTotalDebtUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidationCall"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintUnbacked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintedToTreasury"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Repay"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveUsedAsCollateralDisabled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveUsedAsCollateralEnabled"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Supply"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserEModeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface BackUnbackedEventObject {
  reserve: string;
  backer: string;
  amount: BigNumber;
  fee: BigNumber;
}
export type BackUnbackedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  BackUnbackedEventObject
>;

export type BackUnbackedEventFilter = TypedEventFilter<BackUnbackedEvent>;

export interface BorrowEventObject {
  reserve: string;
  user: string;
  onBehalfOf: string;
  amount: BigNumber;
  interestRateMode: number;
  borrowRate: BigNumber;
  referralCode: number;
}
export type BorrowEvent = TypedEvent<
  [string, string, string, BigNumber, number, BigNumber, number],
  BorrowEventObject
>;

export type BorrowEventFilter = TypedEventFilter<BorrowEvent>;

export interface FlashLoanEventObject {
  target: string;
  initiator: string;
  asset: string;
  amount: BigNumber;
  interestRateMode: number;
  premium: BigNumber;
  referralCode: number;
}
export type FlashLoanEvent = TypedEvent<
  [string, string, string, BigNumber, number, BigNumber, number],
  FlashLoanEventObject
>;

export type FlashLoanEventFilter = TypedEventFilter<FlashLoanEvent>;

export interface IsolationModeTotalDebtUpdatedEventObject {
  asset: string;
  totalDebt: BigNumber;
}
export type IsolationModeTotalDebtUpdatedEvent = TypedEvent<
  [string, BigNumber],
  IsolationModeTotalDebtUpdatedEventObject
>;

export type IsolationModeTotalDebtUpdatedEventFilter =
  TypedEventFilter<IsolationModeTotalDebtUpdatedEvent>;

export interface LiquidationCallEventObject {
  collateralAsset: string;
  debtAsset: string;
  user: string;
  debtToCover: BigNumber;
  liquidatedCollateralAmount: BigNumber;
  liquidator: string;
  receiveAToken: boolean;
}
export type LiquidationCallEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, boolean],
  LiquidationCallEventObject
>;

export type LiquidationCallEventFilter = TypedEventFilter<LiquidationCallEvent>;

export interface MintUnbackedEventObject {
  reserve: string;
  user: string;
  onBehalfOf: string;
  amount: BigNumber;
  referralCode: number;
}
export type MintUnbackedEvent = TypedEvent<
  [string, string, string, BigNumber, number],
  MintUnbackedEventObject
>;

export type MintUnbackedEventFilter = TypedEventFilter<MintUnbackedEvent>;

export interface MintedToTreasuryEventObject {
  reserve: string;
  amountMinted: BigNumber;
}
export type MintedToTreasuryEvent = TypedEvent<
  [string, BigNumber],
  MintedToTreasuryEventObject
>;

export type MintedToTreasuryEventFilter =
  TypedEventFilter<MintedToTreasuryEvent>;

export interface RepayEventObject {
  reserve: string;
  user: string;
  repayer: string;
  amount: BigNumber;
  useATokens: boolean;
}
export type RepayEvent = TypedEvent<
  [string, string, string, BigNumber, boolean],
  RepayEventObject
>;

export type RepayEventFilter = TypedEventFilter<RepayEvent>;

export interface ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventObject {
  reserve: string;
  liquidityRate: BigNumber;
  stableBorrowRate: BigNumber;
  variableBorrowRate: BigNumber;
  liquidityIndex: BigNumber;
  variableBorrowIndex: BigNumber;
}
export type ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_Event =
  TypedEvent<
    [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
    ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventObject
  >;

export type ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventFilter =
  TypedEventFilter<ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_Event>;

export interface ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventObject {
  reserve: string;
  liquidityRate: BigNumber;
  stableBorrowRate: BigNumber;
  variableBorrowRate: BigNumber;
  liquidityIndex: BigNumber;
  variableBorrowIndex: BigNumber;
}

export interface ReserveUsedAsCollateralDisabledEventObject {
  reserve: string;
  user: string;
}
export type ReserveUsedAsCollateralDisabledEvent = TypedEvent<
  [string, string],
  ReserveUsedAsCollateralDisabledEventObject
>;

export type ReserveUsedAsCollateralDisabledEventFilter =
  TypedEventFilter<ReserveUsedAsCollateralDisabledEvent>;

export interface ReserveUsedAsCollateralEnabledEventObject {
  reserve: string;
  user: string;
}
export type ReserveUsedAsCollateralEnabledEvent = TypedEvent<
  [string, string],
  ReserveUsedAsCollateralEnabledEventObject
>;

export type ReserveUsedAsCollateralEnabledEventFilter =
  TypedEventFilter<ReserveUsedAsCollateralEnabledEvent>;

export interface SupplyEventObject {
  reserve: string;
  user: string;
  onBehalfOf: string;
  amount: BigNumber;
  referralCode: number;
}
export type SupplyEvent = TypedEvent<
  [string, string, string, BigNumber, number],
  SupplyEventObject
>;

export type SupplyEventFilter = TypedEventFilter<SupplyEvent>;

export interface UserEModeSetEventObject {
  user: string;
  categoryId: number;
}
export type UserEModeSetEvent = TypedEvent<
  [string, number],
  UserEModeSetEventObject
>;

export type UserEModeSetEventFilter = TypedEventFilter<UserEModeSetEvent>;

export interface WithdrawEventObject {
  reserve: string;
  user: string;
  to: string;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, string, string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface PoolABI extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolABIInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getEModeCategoryData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[DataTypes.EModeCategoryLegacyStructOutput]>;

    FLASHLOAN_PREMIUM_TOTAL(overrides?: CallOverrides): Promise<[BigNumber]>;

    getReserveData(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ReserveDataLegacyStructOutput]>;

    deposit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getLiquidationLogic(overrides?: CallOverrides): Promise<[string]>;

    getReservesList(overrides?: CallOverrides): Promise<[string[]]>;

    getUserAccountData(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalCollateralBase: BigNumber;
        totalDebtBase: BigNumber;
        availableBorrowsBase: BigNumber;
        currentLiquidationThreshold: BigNumber;
        ltv: BigNumber;
        healthFactor: BigNumber;
      }
    >;

    syncRatesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getEModeCategoryCollateralConfig(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[DataTypes.CollateralConfigStructOutput]>;

    updateBridgeProtocolFee(
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    repayWithPermit(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    configureEModeCategory(
      id: BigNumberish,
      category: DataTypes.EModeCategoryBaseConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    repayWithATokens(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getSupplyLogic(overrides?: CallOverrides): Promise<[string]>;

    setUserEMode(
      categoryId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateFlashloanPremiums(
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    MAX_NUMBER_RESERVES(overrides?: CallOverrides): Promise<[number]>;

    repay(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBridgeLogic(overrides?: CallOverrides): Promise<[string]>;

    flashLoan(
      receiverAddress: string,
      assets: string[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: string,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getReserveDataExtended(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ReserveDataStructOutput]>;

    getBorrowLogic(overrides?: CallOverrides): Promise<[string]>;

    getReservesCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    supply(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getFlashLoanLogic(overrides?: CallOverrides): Promise<[string]>;

    POOL_REVISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEModeCategoryLabel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    finalizeTransfer(
      asset: string,
      from: string,
      to: string,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    initialize(
      provider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<[string]>;

    initReserve(
      asset: string,
      aTokenAddress: string,
      variableDebtAddress: string,
      interestRateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getEModeLogic(overrides?: CallOverrides): Promise<[string]>;

    flashLoanSimple(
      receiverAddress: string,
      asset: string,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getReserveNormalizedVariableDebt(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    configureEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      borrowableBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getReserveNormalizedIncome(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    borrow(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    resetIsolationModeTotalDebt(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    mintToTreasury(
      assets: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    backUnbacked(
      asset: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    BRIDGE_PROTOCOL_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    liquidationCall(
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    configureEModeCategoryCollateralBitmap(
      id: BigNumberish,
      collateralBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getPoolLogic(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      asset: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getUserEMode(user: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getConfiguration(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ReserveConfigurationMapStructOutput]>;

    rescueTokens(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLiquidationGracePeriod(
      asset: string,
      until: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supplyWithPermit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getUserConfiguration(
      user: string,
      overrides?: CallOverrides
    ): Promise<[DataTypes.UserConfigurationMapStructOutput]>;

    syncIndexesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getVirtualUnderlyingBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    mintUnbacked(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getReserveAddressById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    FLASHLOAN_PREMIUM_TO_PROTOCOL(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEModeCategoryCollateralBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setUserUseReserveAsCollateral(
      asset: string,
      useAsCollateral: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    dropReserve(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setConfiguration(
      asset: string,
      configuration: DataTypes.ReserveConfigurationMapStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setReserveInterestRateStrategyAddress(
      asset: string,
      rateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getLiquidationGracePeriod(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getEModeCategoryData(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<DataTypes.EModeCategoryLegacyStructOutput>;

  FLASHLOAN_PREMIUM_TOTAL(overrides?: CallOverrides): Promise<BigNumber>;

  getReserveData(
    asset: string,
    overrides?: CallOverrides
  ): Promise<DataTypes.ReserveDataLegacyStructOutput>;

  deposit(
    asset: string,
    amount: BigNumberish,
    onBehalfOf: string,
    referralCode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getLiquidationLogic(overrides?: CallOverrides): Promise<string>;

  getReservesList(overrides?: CallOverrides): Promise<string[]>;

  getUserAccountData(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      totalCollateralBase: BigNumber;
      totalDebtBase: BigNumber;
      availableBorrowsBase: BigNumber;
      currentLiquidationThreshold: BigNumber;
      ltv: BigNumber;
      healthFactor: BigNumber;
    }
  >;

  syncRatesState(
    asset: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getEModeCategoryCollateralConfig(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<DataTypes.CollateralConfigStructOutput>;

  updateBridgeProtocolFee(
    protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  repayWithPermit(
    asset: string,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    onBehalfOf: string,
    deadline: BigNumberish,
    permitV: BigNumberish,
    permitR: BytesLike,
    permitS: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  configureEModeCategory(
    id: BigNumberish,
    category: DataTypes.EModeCategoryBaseConfigurationStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  repayWithATokens(
    asset: string,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getSupplyLogic(overrides?: CallOverrides): Promise<string>;

  setUserEMode(
    categoryId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateFlashloanPremiums(
    flashLoanPremiumTotal: BigNumberish,
    flashLoanPremiumToProtocol: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  MAX_NUMBER_RESERVES(overrides?: CallOverrides): Promise<number>;

  repay(
    asset: string,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    onBehalfOf: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBridgeLogic(overrides?: CallOverrides): Promise<string>;

  flashLoan(
    receiverAddress: string,
    assets: string[],
    amounts: BigNumberish[],
    interestRateModes: BigNumberish[],
    onBehalfOf: string,
    params: BytesLike,
    referralCode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getEModeCategoryBorrowableBitmap(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getReserveDataExtended(
    asset: string,
    overrides?: CallOverrides
  ): Promise<DataTypes.ReserveDataStructOutput>;

  getBorrowLogic(overrides?: CallOverrides): Promise<string>;

  getReservesCount(overrides?: CallOverrides): Promise<BigNumber>;

  supply(
    asset: string,
    amount: BigNumberish,
    onBehalfOf: string,
    referralCode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getFlashLoanLogic(overrides?: CallOverrides): Promise<string>;

  POOL_REVISION(overrides?: CallOverrides): Promise<BigNumber>;

  getEModeCategoryLabel(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  finalizeTransfer(
    asset: string,
    from: string,
    to: string,
    amount: BigNumberish,
    balanceFromBefore: BigNumberish,
    balanceToBefore: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  initialize(
    provider: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

  initReserve(
    asset: string,
    aTokenAddress: string,
    variableDebtAddress: string,
    interestRateStrategyAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getEModeLogic(overrides?: CallOverrides): Promise<string>;

  flashLoanSimple(
    receiverAddress: string,
    asset: string,
    amount: BigNumberish,
    params: BytesLike,
    referralCode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getReserveNormalizedVariableDebt(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  configureEModeCategoryBorrowableBitmap(
    id: BigNumberish,
    borrowableBitmap: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getReserveNormalizedIncome(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  borrow(
    asset: string,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    referralCode: BigNumberish,
    onBehalfOf: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  resetIsolationModeTotalDebt(
    asset: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  mintToTreasury(
    assets: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  backUnbacked(
    asset: string,
    amount: BigNumberish,
    fee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  BRIDGE_PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  liquidationCall(
    collateralAsset: string,
    debtAsset: string,
    user: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  configureEModeCategoryCollateralBitmap(
    id: BigNumberish,
    collateralBitmap: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getPoolLogic(overrides?: CallOverrides): Promise<string>;

  withdraw(
    asset: string,
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getUserEMode(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  getConfiguration(
    asset: string,
    overrides?: CallOverrides
  ): Promise<DataTypes.ReserveConfigurationMapStructOutput>;

  rescueTokens(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLiquidationGracePeriod(
    asset: string,
    until: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supplyWithPermit(
    asset: string,
    amount: BigNumberish,
    onBehalfOf: string,
    referralCode: BigNumberish,
    deadline: BigNumberish,
    permitV: BigNumberish,
    permitR: BytesLike,
    permitS: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getUserConfiguration(
    user: string,
    overrides?: CallOverrides
  ): Promise<DataTypes.UserConfigurationMapStructOutput>;

  syncIndexesState(
    asset: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getVirtualUnderlyingBalance(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  mintUnbacked(
    asset: string,
    amount: BigNumberish,
    onBehalfOf: string,
    referralCode: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getReserveAddressById(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  FLASHLOAN_PREMIUM_TO_PROTOCOL(overrides?: CallOverrides): Promise<BigNumber>;

  getEModeCategoryCollateralBitmap(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setUserUseReserveAsCollateral(
    asset: string,
    useAsCollateral: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  dropReserve(
    asset: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setConfiguration(
    asset: string,
    configuration: DataTypes.ReserveConfigurationMapStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setReserveInterestRateStrategyAddress(
    asset: string,
    rateStrategyAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getLiquidationGracePeriod(
    asset: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getEModeCategoryData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<DataTypes.EModeCategoryLegacyStructOutput>;

    FLASHLOAN_PREMIUM_TOTAL(overrides?: CallOverrides): Promise<BigNumber>;

    getReserveData(
      asset: string,
      overrides?: CallOverrides
    ): Promise<DataTypes.ReserveDataLegacyStructOutput>;

    deposit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getLiquidationLogic(overrides?: CallOverrides): Promise<string>;

    getReservesList(overrides?: CallOverrides): Promise<string[]>;

    getUserAccountData(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalCollateralBase: BigNumber;
        totalDebtBase: BigNumber;
        availableBorrowsBase: BigNumber;
        currentLiquidationThreshold: BigNumber;
        ltv: BigNumber;
        healthFactor: BigNumber;
      }
    >;

    syncRatesState(asset: string, overrides?: CallOverrides): Promise<void>;

    getEModeCategoryCollateralConfig(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<DataTypes.CollateralConfigStructOutput>;

    updateBridgeProtocolFee(
      protocolFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    repayWithPermit(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    configureEModeCategory(
      id: BigNumberish,
      category: DataTypes.EModeCategoryBaseConfigurationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    repayWithATokens(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupplyLogic(overrides?: CallOverrides): Promise<string>;

    setUserEMode(
      categoryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFlashloanPremiums(
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    MAX_NUMBER_RESERVES(overrides?: CallOverrides): Promise<number>;

    repay(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBridgeLogic(overrides?: CallOverrides): Promise<string>;

    flashLoan(
      receiverAddress: string,
      assets: string[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: string,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReserveDataExtended(
      asset: string,
      overrides?: CallOverrides
    ): Promise<DataTypes.ReserveDataStructOutput>;

    getBorrowLogic(overrides?: CallOverrides): Promise<string>;

    getReservesCount(overrides?: CallOverrides): Promise<BigNumber>;

    supply(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getFlashLoanLogic(overrides?: CallOverrides): Promise<string>;

    POOL_REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    getEModeCategoryLabel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    finalizeTransfer(
      asset: string,
      from: string,
      to: string,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(provider: string, overrides?: CallOverrides): Promise<void>;

    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

    initReserve(
      asset: string,
      aTokenAddress: string,
      variableDebtAddress: string,
      interestRateStrategyAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getEModeLogic(overrides?: CallOverrides): Promise<string>;

    flashLoanSimple(
      receiverAddress: string,
      asset: string,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getReserveNormalizedVariableDebt(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    configureEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      borrowableBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getReserveNormalizedIncome(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrow(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    resetIsolationModeTotalDebt(
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintToTreasury(assets: string[], overrides?: CallOverrides): Promise<void>;

    backUnbacked(
      asset: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BRIDGE_PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    liquidationCall(
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    configureEModeCategoryCollateralBitmap(
      id: BigNumberish,
      collateralBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPoolLogic(overrides?: CallOverrides): Promise<string>;

    withdraw(
      asset: string,
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserEMode(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getConfiguration(
      asset: string,
      overrides?: CallOverrides
    ): Promise<DataTypes.ReserveConfigurationMapStructOutput>;

    rescueTokens(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLiquidationGracePeriod(
      asset: string,
      until: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supplyWithPermit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getUserConfiguration(
      user: string,
      overrides?: CallOverrides
    ): Promise<DataTypes.UserConfigurationMapStructOutput>;

    syncIndexesState(asset: string, overrides?: CallOverrides): Promise<void>;

    getVirtualUnderlyingBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintUnbacked(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getReserveAddressById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    FLASHLOAN_PREMIUM_TO_PROTOCOL(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEModeCategoryCollateralBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setUserUseReserveAsCollateral(
      asset: string,
      useAsCollateral: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    dropReserve(asset: string, overrides?: CallOverrides): Promise<void>;

    setConfiguration(
      asset: string,
      configuration: DataTypes.ReserveConfigurationMapStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setReserveInterestRateStrategyAddress(
      asset: string,
      rateStrategyAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLiquidationGracePeriod(
      asset: string,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    "BackUnbacked(address,address,uint256,uint256)"(
      reserve?: string | null,
      backer?: string | null,
      amount?: null,
      fee?: null
    ): BackUnbackedEventFilter;
    BackUnbacked(
      reserve?: string | null,
      backer?: string | null,
      amount?: null,
      fee?: null
    ): BackUnbackedEventFilter;

    "Borrow(address,address,address,uint256,uint8,uint256,uint16)"(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      interestRateMode?: null,
      borrowRate?: null,
      referralCode?: BigNumberish | null
    ): BorrowEventFilter;
    Borrow(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      interestRateMode?: null,
      borrowRate?: null,
      referralCode?: BigNumberish | null
    ): BorrowEventFilter;

    "FlashLoan(address,address,address,uint256,uint8,uint256,uint16)"(
      target?: string | null,
      initiator?: null,
      asset?: string | null,
      amount?: null,
      interestRateMode?: null,
      premium?: null,
      referralCode?: BigNumberish | null
    ): FlashLoanEventFilter;
    FlashLoan(
      target?: string | null,
      initiator?: null,
      asset?: string | null,
      amount?: null,
      interestRateMode?: null,
      premium?: null,
      referralCode?: BigNumberish | null
    ): FlashLoanEventFilter;

    "IsolationModeTotalDebtUpdated(address,uint256)"(
      asset?: string | null,
      totalDebt?: null
    ): IsolationModeTotalDebtUpdatedEventFilter;
    IsolationModeTotalDebtUpdated(
      asset?: string | null,
      totalDebt?: null
    ): IsolationModeTotalDebtUpdatedEventFilter;

    "LiquidationCall(address,address,address,uint256,uint256,address,bool)"(
      collateralAsset?: string | null,
      debtAsset?: string | null,
      user?: string | null,
      debtToCover?: null,
      liquidatedCollateralAmount?: null,
      liquidator?: null,
      receiveAToken?: null
    ): LiquidationCallEventFilter;
    LiquidationCall(
      collateralAsset?: string | null,
      debtAsset?: string | null,
      user?: string | null,
      debtToCover?: null,
      liquidatedCollateralAmount?: null,
      liquidator?: null,
      receiveAToken?: null
    ): LiquidationCallEventFilter;

    "MintUnbacked(address,address,address,uint256,uint16)"(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      referralCode?: BigNumberish | null
    ): MintUnbackedEventFilter;
    MintUnbacked(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      referralCode?: BigNumberish | null
    ): MintUnbackedEventFilter;

    "MintedToTreasury(address,uint256)"(
      reserve?: string | null,
      amountMinted?: null
    ): MintedToTreasuryEventFilter;
    MintedToTreasury(
      reserve?: string | null,
      amountMinted?: null
    ): MintedToTreasuryEventFilter;

    "Repay(address,address,address,uint256,bool)"(
      reserve?: string | null,
      user?: string | null,
      repayer?: string | null,
      amount?: null,
      useATokens?: null
    ): RepayEventFilter;
    Repay(
      reserve?: string | null,
      user?: string | null,
      repayer?: string | null,
      amount?: null,
      useATokens?: null
    ): RepayEventFilter;

    "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"(
      reserve?: string | null,
      liquidityRate?: null,
      stableBorrowRate?: null,
      variableBorrowRate?: null,
      liquidityIndex?: null,
      variableBorrowIndex?: null
    ): ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventFilter;
    "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"(
      reserve?: string | null,
      liquidityRate?: null,
      stableBorrowRate?: null,
      variableBorrowRate?: null,
      liquidityIndex?: null,
      variableBorrowIndex?: null
    ): ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_EventFilter;

    "ReserveUsedAsCollateralDisabled(address,address)"(
      reserve?: string | null,
      user?: string | null
    ): ReserveUsedAsCollateralDisabledEventFilter;
    ReserveUsedAsCollateralDisabled(
      reserve?: string | null,
      user?: string | null
    ): ReserveUsedAsCollateralDisabledEventFilter;

    "ReserveUsedAsCollateralEnabled(address,address)"(
      reserve?: string | null,
      user?: string | null
    ): ReserveUsedAsCollateralEnabledEventFilter;
    ReserveUsedAsCollateralEnabled(
      reserve?: string | null,
      user?: string | null
    ): ReserveUsedAsCollateralEnabledEventFilter;

    "Supply(address,address,address,uint256,uint16)"(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      referralCode?: BigNumberish | null
    ): SupplyEventFilter;
    Supply(
      reserve?: string | null,
      user?: null,
      onBehalfOf?: string | null,
      amount?: null,
      referralCode?: BigNumberish | null
    ): SupplyEventFilter;

    "UserEModeSet(address,uint8)"(
      user?: string | null,
      categoryId?: null
    ): UserEModeSetEventFilter;
    UserEModeSet(
      user?: string | null,
      categoryId?: null
    ): UserEModeSetEventFilter;

    "Withdraw(address,address,address,uint256)"(
      reserve?: string | null,
      user?: string | null,
      to?: string | null,
      amount?: null
    ): WithdrawEventFilter;
    Withdraw(
      reserve?: string | null,
      user?: string | null,
      to?: string | null,
      amount?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    getEModeCategoryData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FLASHLOAN_PREMIUM_TOTAL(overrides?: CallOverrides): Promise<BigNumber>;

    getReserveData(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getLiquidationLogic(overrides?: CallOverrides): Promise<BigNumber>;

    getReservesList(overrides?: CallOverrides): Promise<BigNumber>;

    getUserAccountData(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    syncRatesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getEModeCategoryCollateralConfig(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateBridgeProtocolFee(
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    repayWithPermit(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    configureEModeCategory(
      id: BigNumberish,
      category: DataTypes.EModeCategoryBaseConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    repayWithATokens(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getSupplyLogic(overrides?: CallOverrides): Promise<BigNumber>;

    setUserEMode(
      categoryId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateFlashloanPremiums(
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    MAX_NUMBER_RESERVES(overrides?: CallOverrides): Promise<BigNumber>;

    repay(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBridgeLogic(overrides?: CallOverrides): Promise<BigNumber>;

    flashLoan(
      receiverAddress: string,
      assets: string[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: string,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReserveDataExtended(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBorrowLogic(overrides?: CallOverrides): Promise<BigNumber>;

    getReservesCount(overrides?: CallOverrides): Promise<BigNumber>;

    supply(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getFlashLoanLogic(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    getEModeCategoryLabel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    finalizeTransfer(
      asset: string,
      from: string,
      to: string,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    initialize(
      provider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<BigNumber>;

    initReserve(
      asset: string,
      aTokenAddress: string,
      variableDebtAddress: string,
      interestRateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getEModeLogic(overrides?: CallOverrides): Promise<BigNumber>;

    flashLoanSimple(
      receiverAddress: string,
      asset: string,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getReserveNormalizedVariableDebt(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    configureEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      borrowableBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getReserveNormalizedIncome(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrow(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    resetIsolationModeTotalDebt(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    mintToTreasury(
      assets: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    backUnbacked(
      asset: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    BRIDGE_PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    liquidationCall(
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    configureEModeCategoryCollateralBitmap(
      id: BigNumberish,
      collateralBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getPoolLogic(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      asset: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getUserEMode(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getConfiguration(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rescueTokens(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLiquidationGracePeriod(
      asset: string,
      until: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supplyWithPermit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getUserConfiguration(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    syncIndexesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getVirtualUnderlyingBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintUnbacked(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getReserveAddressById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FLASHLOAN_PREMIUM_TO_PROTOCOL(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEModeCategoryCollateralBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setUserUseReserveAsCollateral(
      asset: string,
      useAsCollateral: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    dropReserve(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setConfiguration(
      asset: string,
      configuration: DataTypes.ReserveConfigurationMapStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setReserveInterestRateStrategyAddress(
      asset: string,
      rateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getLiquidationGracePeriod(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getEModeCategoryData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FLASHLOAN_PREMIUM_TOTAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserveData(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getLiquidationLogic(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReservesList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserAccountData(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    syncRatesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getEModeCategoryCollateralConfig(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateBridgeProtocolFee(
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    repayWithPermit(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    configureEModeCategory(
      id: BigNumberish,
      category: DataTypes.EModeCategoryBaseConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    repayWithATokens(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getSupplyLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUserEMode(
      categoryId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateFlashloanPremiums(
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    MAX_NUMBER_RESERVES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    repay(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBridgeLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashLoan(
      receiverAddress: string,
      assets: string[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: string,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserveDataExtended(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBorrowLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReservesCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supply(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getFlashLoanLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    POOL_REVISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEModeCategoryLabel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finalizeTransfer(
      asset: string,
      from: string,
      to: string,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    initialize(
      provider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ADDRESSES_PROVIDER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initReserve(
      asset: string,
      aTokenAddress: string,
      variableDebtAddress: string,
      interestRateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getEModeLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashLoanSimple(
      receiverAddress: string,
      asset: string,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getReserveNormalizedVariableDebt(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    configureEModeCategoryBorrowableBitmap(
      id: BigNumberish,
      borrowableBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getReserveNormalizedIncome(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    borrow(
      asset: string,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    resetIsolationModeTotalDebt(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    mintToTreasury(
      assets: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    backUnbacked(
      asset: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    BRIDGE_PROTOCOL_FEE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidationCall(
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    configureEModeCategoryCollateralBitmap(
      id: BigNumberish,
      collateralBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getPoolLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      asset: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getUserEMode(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfiguration(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rescueTokens(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLiquidationGracePeriod(
      asset: string,
      until: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supplyWithPermit(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getUserConfiguration(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    syncIndexesState(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getVirtualUnderlyingBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintUnbacked(
      asset: string,
      amount: BigNumberish,
      onBehalfOf: string,
      referralCode: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getReserveAddressById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FLASHLOAN_PREMIUM_TO_PROTOCOL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEModeCategoryCollateralBitmap(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setUserUseReserveAsCollateral(
      asset: string,
      useAsCollateral: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    dropReserve(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setConfiguration(
      asset: string,
      configuration: DataTypes.ReserveConfigurationMapStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setReserveInterestRateStrategyAddress(
      asset: string,
      rateStrategyAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getLiquidationGracePeriod(
      asset: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
